### ISSUE TITLE
Error building hcc

### ISSUE THREAD

**Issue by adityaatluri** [RadeonOpenCompute/HCC-Native-GCN-ISA#3]
hcc-native-gcn-isa/hcc/build/compiler/bin/clamp-hsatools: line 116: AMDPHDRS-NOTFOUND: command not found
clang-3.5: error: unable to execute command: No such file or directory
clang-3.5: error: linker command failed due to signal (use -v to see invocation)
make[2]: *** [bin/clamp-config] Error 255
make[1]: *** [lib/CMakeFiles/clamp-config.dir/all] Error 2
make: *** [all] Error 2

**Comment by tstellarAMD** [comment]
Please follow the build instructions on the wiki: https://github.com/RadeonOpenCompute/HCC-Native-GCN-ISA/wiki#build-instructions

**Comment by adityaatluri** [comment]
Oh. I got it working after submitting this. Thanks!
