### ISSUE TITLE
HC compile syntax / includes?

### ISSUE THREAD

**Issue by zgu153522** [RadeonOpenCompute/HCC-Native-GCN-ISA#4]
I think this is a case of me not knowing how to use this particular version of HCC.  The AMP compliance test works.  But when I follow the HC->HSA syntax to compile HC code, I get:

```
hcc `hcc-config --cxxflags --ldflags` saxpy_array.cpp -o saxpy_array.out
hcc-config: command not found
In file included from saxpy_array.cpp:3:
In file included from /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/random:35:
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/c++0x_warning.h:32:2: error: 
      This file requires compiler and library support for the ISO C++ 2011
      standard. This support is currently experimental, and must be enabled with
      the -std=c++11 or -std=gnu++11 compiler options.
#error This file requires compiler and library support for the \
 ^
saxpy_array.cpp:10:10: fatal error: 'hc.hpp' file not found
#include <hc.hpp>
         ^
2 errors generated.
```

If I add the -I option to either /hcc/build/include or /hcc/include I instead get a long list of errors.  What is the correct syntax for HC->GCN hcc to build HC code?

**Comment by zgu153522** [comment]
I'm able to get this to work now with:

`hcc -hc -stdlib=libc++ -I/home/pbamd1/hcc/include -I/usr/include -I/home/pbamd1/hcc/build/compiler/lib/clang/3.5.0/include/ saxpy_array.cpp -hc -L/home/pbamd1/hcc/build/lib -Wl,--rpath=/home/pbamd1/hcc/build/lib -lc++ -lc++abi -ldl -lpthread -Wl,--whole-archive -lmcwamp -Wl,--no-whole-archive -o saxpy_array.out -g`

I basically took the AMP conformance test call, replaced clamp with hcc, added -hc, and removed anything that looks like it's related to AMP.  However, I'm still not sure which parts of the above are actually necessary, and which parts are ignored or might even cause problems.

**Comment by zgu153522** [comment]
I encountered a problem when using a kernel with a call to __shfl:

```
hcc -hc -stdlib=libc++ -I/home/pbamd1/hcc/include -I/usr/include -I/home/pbamd1/hcc/build/compiler/lib/clang/3.5.0/include/ proto3.cpp -hc -L/home/pbamd1/hcc/build/lib -Wl,--rpath=/home/pbamd1/hcc/build/lib -lc++ -lc++abi -ldl -lpthread -Wl,--whole-archive -lmcwamp -Wl,--no-whole-archive -o proto3.out -g
error: <unknown>:0:0: in function ZZ4mainEN3_EC__019__cxxamp_trampolineEPmiiPiii void (i64 addrspace(1)*, i32, i32, i32 addrspace(1)*, i32, i32): unsupported call to function __hsail_activelanepermute_b32

Failed to get ehdr: invalid `Elf' handle
clang-3.5: error: linker command failed with exit code 1 (use -v to see invocation)
```

I'm fairly certain this means I don't have the right linker command line options, but I'm not able to figure out what the correct options should be to use __shfl.

**Comment by scchan** [comment]
Could you talk about how you resolved the first issue with hc.hpp header?  It looks like you were missing libc++ on your system?


The support for __shfl for the GCN backend is currently in a separate branch (shfl_ds_perm).  We should be able to merge it into master in few days after some cleanup.

**Comment by zgu153522** [comment]
> Could you talk about how you resolved the first issue with hc.hpp header? It looks like you were missing libc++ on your system?

> The support for __shfl for the GCN backend is currently in a separate branch (shfl_ds_perm). We should be able to merge it into master in few days after some cleanup.

Hi @scchan the options -stdlib=libc++ -I/home/pbamd1/hcc/include -I/home/pbamd1/hcc/build/compiler/lib/clang/3.5.0/include/ resolves the hc.hpp not found issue.

Also, would it be possible for you to comment on whether mul24 will be supported in HC?  Additionally, we would love to see support for GDS access at some point.  Perhaps these can be added as extensions to the core HC API.

**Comment by scchan** [comment]
For mul24, our GCN backend already supports it and it would be pretty easy for us to add the builtins support to expose them in hcc.  

For GDS, we currently don't have a plan to support it and as you may already knew, it could be tricky as it impacts multiple components such as the runtime and the compiler but I'll forward your feedback to our engineering teams.

**Comment by zgu153522** [comment]
Thanks, I'm closing the issue as it relates to the original question.
