### ISSUE TITLE
can't fetch roc-1.0 branch

### ISSUE THREAD

**Issue by yan-ming** [RadeonOpenCompute/HCC-Native-GCN-ISA#5]
Hi @tstellarAMD,

Since somehow the branch name of hcc has been changed to `roc-1.0.x`, the following line in wiki will fail:

`repo init -u https://github.com/RadeonOpenCompute/HCC-Native-GCN-ISA.git -b roc-1.0`

```
fatal: Couldn't find remote ref refs/heads/roc-1.0
Unexpected end of command stream
```

Looks like we should updated the manifest file of repo tool with the new branch name?

**Comment by yan-ming** [comment]
@scchan, it looks like the branch name has been changed last week?

**Comment by tstellarAMD** [comment]
I will fix the wiki, but did you actually try this?  It should still work since there is a branch called roc-1.0.

**Comment by tstellarAMD** [comment]
Oh, I see the error message is for the hcc ref, and not the manifest ref.

**Comment by tstellarAMD** [comment]
I've updated the wiki.  Thanks!

**Comment by yan-ming** [comment]
Cool cool, it works for me now, thanks for your prompt response!
