### ISSUE TITLE
repo is not available from apt

### ISSUE THREAD

**Issue by yan-ming** [RadeonOpenCompute/HCC-Native-GCN-ISA#6]
I thought this should be just a typo here?

```
apt-get install cmake git repo libelf-dev libc++abi-dev libc++-dev 
```

https://github.com/RadeonOpenCompute/HCC-Native-GCN-ISA/wiki#installing-dependencies-on-ubuntu

**Comment by Dekken** [comment]
curl https://storage.googleapis.com/git-repo-downloads/repo > repo
chmod +x repo

**Comment by scchan** [comment]
I removed "repo" from apt-get
